### ISSUE TITLE
Selecting QEMU as a backend gives 500 error

### ISSUE THREAD

**Issue by Adrianzatreanu** [vmck/vmck#49]
Currently running the docker instance with ``--env BACKEND=qemu`` will give an error:

```
/opt/vagrant/embedded/lib/ruby/2.4.0/json/common.rb:156:in `parse': 751: unexpected token at '<h1>Server Error (500)</h1>' (JSON::ParserError)
    from /opt/vagrant/embedded/lib/ruby/2.4.0/json/common.rb:156:in `parse'
    from /home/adrian/.vagrant.d/gems/2.4.4/gems/vagrant-vmck-0.0.1/lib/vagrant-vmck/client.rb:23:in `request'
    from /home/adrian/.vagrant.d/gems/2.4.4/gems/vagrant-vmck-0.0.1/lib/vagrant-vmck/client.rb:39:in `create'
    from /home/adrian/.vagrant.d/gems/2.4.4/gems/vagrant-vmck-0.0.1/lib/vagrant-vmck/action/create.rb:18:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
    from /home/adrian/.vagrant.d/gems/2.4.4/gems/vagrant-vmck-0.0.1/lib/vagrant-vmck/action/connect_vmck.rb:17:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/warden.rb:50:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `block in run'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/action/runner.rb:102:in `run'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:238:in `action_raw'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:209:in `block in action'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/environment.rb:615:in `lock'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:195:in `call'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/machine.rb:195:in `action'
    from /opt/vagrant/embedded/gems/2.2.4/gems/vagrant-2.2.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

Full command ran:
```
docker run --detach --restart always \
  --name cluster \
  --volume /opt/cluster/var:/opt/cluster/var \
  --volume /opt/vmck/var:/opt/vmck/var \
  --volume /var/run/docker.sock:/var/run/docker.sock:ro \
  --privileged \
  --net host \
  --env NOMAD_CLIENT_INTERFACE=liquid-bridge \
  --env HOSTNAME=127.0.0.1 \
  --env SECRET_KEY=foo \
  --env BACKEND=qemu \
  mgax/vmck
```

**Comment by gabriel-v** [comment]
try it again with these variables:

https://github.com/liquidinvestigations/node/blob/c24a1c675afea8a7225217f31fd4143be1c78f0c/templates/drone.nomad#L76

In our setup we have a nginx instance that serves the `.qcow2` files, you will need to replicate that too and set `QEMU_IMAGE_URL`.

**Comment by mgax** [comment]
We're using qemu in production with much happiness and it works fine. Closing.
